POSITIVE_QUESTIONS = [
    {"question": "Can I sponsor my parents for permanent residence if I currently live in Quebec?", "expected": 1},
    {"question": "Can I apply for Express Entry while on a Post-Graduation Work Permit?", "expected": 1},
    {"question": "Can I travel outside Canada while my PR application is in process?", "expected": 1},
    {"question": "Can international students work full-time during scheduled school breaks?", "expected": 1},
    {"question": "Can a refugee claimant apply for a study permit?", "expected": 1},
    {"question": "Is a police certificate required for most PR applications?", "expected": 1},
    {"question": "Can I restore my temporary resident status within 90 days of losing it?", "expected": 1},
    {"question": "Is biometrics required for most TRV applications?", "expected": 1},
    {"question": "Can employers apply for an LMIA on behalf of a foreign worker?", "expected": 1},
    {"question": "Is travel history considered in visitor visa applications?", "expected": 1},
    {"question": "Can a work permit be issued without an LMIA under certain exemption categories?", "expected": 1},
    {"question": "Can I submit multiple immigration applications as long as I meet eligibility?", "expected": 1},
    {"question": "Are digital photos accepted for immigration applications?", "expected": 1},
    {"question": "Can a dependent spouse work in Canada with an open work permit?", "expected": 1},
    {"question": "Does co-op work count as Canadian work experience for some PR pathways?", "expected": 1},
    {"question": "Can TR to PR applicants travel if they have valid temporary status?", "expected": 1},
    {"question": "Can international students work remotely for a foreign employer?", "expected": 1},
    {"question": "Can a permanent resident sponsor their fiancé(e) through the family class?", "expected": 1},
    {"question": "Can international students open a business in Canada?", "expected": 1},
    {"question": "Can I change my status from visitor to student from inside Canada?", "expected": 1},
    {"question": "Can Canadian citizens pass citizenship automatically to children born abroad in many cases?", "expected": 1},
    {"question": "Can open work permit holders study without a study permit for programs under 6 months?", "expected": 1},
    {"question": "Is medical insurance recommended for visitors to Canada?", "expected": 1},
    {"question": "Can Express Entry applicants update their profile after submitting?", "expected": 1},
    {"question": "Can I hire an immigration consultant if I choose to?", "expected": 1},
    {"question": "Is a valid passport required for all immigration applications?", "expected": 1},
    {"question": "Can PR card renewals be submitted from inside Canada only?", "expected": 1},
    {"question": "Can dual citizens hold two passports when traveling?", "expected": 1},
    {"question": "Can an international student switch schools in Canada?", "expected": 1},
    {"question": "Can I include dependent children in my PR application?", "expected": 1},
    {"question": "Can certain spouses of skilled workers get open work permits?", "expected": 1},
    {"question": "Is biometrics valid for 10 years for most applicants?", "expected": 1},
    {"question": "Can I request GCMS notes on my immigration file?", "expected": 1},
    {"question": "Can refugees apply for permanent residence after being accepted?", "expected": 1},
    {"question": "Is Canadian work experience valuable under Express Entry?", "expected": 1},
    {"question": "Can international students extend their study permits before expiry?", "expected": 1},
    {"question": "Can PR applicants add a newborn child after applying?", "expected": 1},
    {"question": "Can a Canadian citizen sponsor a spouse living outside Canada?", "expected": 1},
    {"question": "Can working holiday participants apply for another permit after expiration if eligible?", "expected": 1},
    {"question": "Is a medical exam required for many long-term permits?", "expected": 1},
    {"question": "Can asylum seekers get work permits while waiting?", "expected": 1},
    {"question": "Can Canadian citizens vote in federal elections?", "expected": 1},
    {"question": "Can international graduates apply for provincial nominee programs?", "expected": 1},
    {"question": "Is it possible to flagpole for certain status changes?", "expected": 1},
    {"question": "Can I apply for a bridging open work permit if eligible?", "expected": 1},
    {"question": "Can I update my address with IRCC online?", "expected": 1},
    {"question": "Is a background check part of the PR process?", "expected": 1},
    {"question": "Can temporary residents apply for a SIN if they have a valid work permit?", "expected": 1},
    {"question": "Can some visitors extend their stay from inside Canada?", "expected": 1},
    {"question": "Can an expired passport delay a work permit application?", "expected": 1},
]

NEGATIVE_QUESTIONS = [
    {"question": "Do I need a job offer to qualify for Express Entry?", "expected": 0},
    {"question": "Are unpaid internships counted as work experience for Express Entry?", "expected": 0},
    {"question": "Does a work permit automatically extend my spouse's status?", "expected": 0},
    {"question": "Is there an age limit that disqualifies applicants from Express Entry?", "expected": 0},
    {"question": "Does Quebec use the Express Entry system for selecting immigrants?", "expected": 0},
    {"question": "Is part-time work enough to qualify for a PGWP?", "expected": 0},
    {"question": "Do all PNP programs require a job offer?", "expected": 0},
    {"question": "Can I re-enter Canada with an expired PR card without a PRTD?", "expected": 0},
    {"question": "Do I need a medical exam for a regular visitor visa?", "expected": 0},
    {"question": "Can I extend a PGWP once it expires under normal rules?", "expected": 0},
    {"question": "Does Canadian volunteer work count toward Express Entry work experience?", "expected": 0},
    {"question": "Can a Canadian citizen generally sponsor a sibling for PR?", "expected": 0},
    {"question": "Does IRCC waive biometrics because of anxiety or stress?", "expected": 0},
    {"question": "Do I need an ECA if I studied in Canada?", "expected": 0},
    {"question": "Is a graduation ceremony considered a valid reason to extend a study permit?", "expected": 0},
    {"question": "Does a visitor visa allow full-time work in Canada?", "expected": 0},
    {"question": "Can I claim EI benefits as an international student without work eligibility?", "expected": 0},
    {"question": "Is a TRV the same as a study permit?", "expected": 0},
    {"question": "Does IRCC guarantee processing times?", "expected": 0},
    {"question": "Can I work in Canada while waiting for a visitor visa decision?", "expected": 0},
    {"question": "Do study permit holders automatically qualify for PR?", "expected": 0},
    {"question": "Does having Canadian relatives automatically increase CRS points?", "expected": 0},
    {"question": "Is a police certificate required for minor children for all applications?", "expected": 0},
    {"question": "Can I stay in Canada indefinitely after my permit expires?", "expected": 0},
    {"question": "Does IRCC allow applicants to skip medical exams if they feel healthy?", "expected": 0},
    {"question": "Can PR holders vote in federal elections?", "expected": 0},
    {"question": "Does Canada offer PR solely based on buying property?", "expected": 0},
    {"question": "Is a work permit guaranteed if my employer applies for an LMIA?", "expected": 0},
    {"question": "Can refugees be deported while their claim is under review?", "expected": 0},
    {"question": "Do international students automatically become eligible for OHIP everywhere?", "expected": 0},
    {"question": "Can I study full-time on a visitor visa without a study permit?", "expected": 0},
    {"question": "Does IRCC accept handwritten application forms?", "expected": 0},
    {"question": "Is sponsorship guaranteed once approved as eligible?", "expected": 0},
    {"question": "Do I need a Canadian job offer to become a citizen?", "expected": 0},
    {"question": "Does Express Entry guarantee an ITA if I meet minimum requirements?", "expected": 0},
    {"question": "Can I apply for a PR card from outside Canada?", "expected": 0},
    {"question": "Is biometrics required every time I apply for a permit?", "expected": 0},
    {"question": "Can I work in Canada without a SIN?", "expected": 0},
    {"question": "Does an eTA allow permanent residency?", "expected": 0},
    {"question": "Can I convert a visitor visa to a work permit without meeting eligibility?", "expected": 0},
    {"question": "Is being married to a Canadian citizen automatic PR?", "expected": 0},
    {"question": "Can minors apply for Express Entry independently?", "expected": 0},
    {"question": "Is English testing optional for most economic immigration streams?", "expected": 0},
    {"question": "Can I submit a PR application without proof of funds when required?", "expected": 0},
    {"question": "Does Canada offer special PR programs for cryptocurrency investors?", "expected": 0},
    {"question": "Do visitor visa holders qualify for provincial health coverage by default?", "expected": 0},
    {"question": "Can I work on a study permit before my program starts?", "expected": 0},
    {"question": "Is a passport photo the same size as a Canadian immigration photo?", "expected": 0},
    {"question": "Can I avoid background checks by hiring a lawyer?", "expected": 0},
    {"question": "Does traveling frequently automatically harm a PR application?", "expected": 0},
]