QUESTIONS_DATA = [
  {"question": "Can I sponsor my parents for permanent residence if I currently live in Quebec?", "expected": 1},
  {"question": "How long does it usually take to process a spousal sponsorship application from India?", "expected": 1},
  {"question": "What documents do I need to prove common-law status for PR sponsorship?", "expected": 1},
  {"question": "If I am on a Post-Graduation Work Permit, can I apply for Express Entry?", "expected": 1},
  {"question": "Does a work permit automatically extend my spouse's study permit?", "expected": 1},
  {"question": "How many points do I get for Canadian work experience under Express Entry?", "expected": 1},
  {"question": "Is there a minimum bank balance required for international students in Canada?", "expected": 1},
  {"question": "Can I travel outside Canada while my PR application is in process?", "expected": 1},
  {"question": "Do I need a job offer to qualify for Express Entry?", "expected": 1},
  {"question": "Can I work full-time during scheduled school breaks as an international student?", "expected": 1},
  {"question": "If I lose my job on a closed work permit, how long do I have to find another employer?", "expected": 1},
  {"question": "Can a refugee claimant apply for a study permit?", "expected": 1},
  {"question": "What is the minimum CRS score needed to receive an ITA?", "expected": 1},
  {"question": "Is a police certificate required for PR applications submitted inside Canada?", "expected": 1},
  {"question": "Can a Canadian citizen sponsor a sibling for PR?", "expected": 1},
  {"question": "How long do I have to live in Canada to apply for citizenship?", "expected": 1},
  {"question": "Does dual citizenship affect my ability to sponsor a spouse?", "expected": 1},
  {"question": "Are unpaid internships counted as work experience for Express Entry?", "expected": 1},
  {"question": "Can I restore my status if my work permit expired two months ago?", "expected": 1},
  {"question": "Do all provinces require a job offer for PNP applications?", "expected": 1},
  {"question": "Is biometrics required for TRV applications inside Canada?", "expected": 1},
  {"question": "Can an international student open a business in Canada?", "expected": 1},
  {"question": "Can my employer apply for an LMIA on my behalf?", "expected": 1},
  {"question": "Does part-time work count toward PGWP eligibility?", "expected": 1},
  {"question": "What happens if my biometrics expire before my PR application is processed?", "expected": 1},
  {"question": "Do I need medical exams for a visitor visa?", "expected": 1},
  {"question": "Can I switch from a visitor visa to a study permit inside Canada?", "expected": 1},
  {"question": "Is there an age limit for Express Entry?", "expected": 1},
  {"question": "Does Quebec accept Express Entry applicants?", "expected": 1},
  {"question": "Can a PR holder sponsor their fiancé(e)?", "expected": 1},
  {"question": "If my PR card expires while abroad, can I still re-enter Canada?", "expected": 1},
  {"question": "How long is an LMIA valid?", "expected": 1},
  {"question": "What happens if my passport expires during a work permit application?", "expected": 1},
  {"question": "Is a graduation ceremony considered a valid reason to extend a study permit?", "expected": 1},
  {"question": "Can international students work remotely for a foreign employer?", "expected": 1},
  {"question": "Is travel history required for a visitor visa?", "expected": 1},
  {"question": "Can a work permit application be processed without an LMIA?", "expected": 1},
  {"question": "Can I submit multiple immigration applications at the same time?", "expected": 1},
  {"question": "Are digital photos accepted for immigration applications?", "expected": 1},
  {"question": "Does applying for a visitor visa affect future PR applications?", "expected": 1},
  {"question": "Can a dependent spouse work in Canada on a study permit?", "expected": 1},
  {"question": "Does co-op work count as Canadian work experience for PR?", "expected": 1},
  {"question": "Can TR to PR applicants travel outside Canada while waiting?", "expected": 1},
  {"question": "Is there a minimum income for sponsoring a spouse?", "expected": 1},
  {"question": "Do I need an ECA if I studied in Canada?", "expected": 1},
  {"question": "Can I extend my PGWP?", "expected": 1},
  {"question": "Do start-up visa applicants need investment secured before applying?", "expected": 1},
  {"question": "Does Canadian volunteer experience count toward PR?", "expected": 1},
  {"question": "Can international students apply for EI benefits?", "expected": 1},
  {"question": "Can a Canadian citizen's child born abroad get Canadian citizenship automatically?", "expected": 1},
]

NEGATIVE_QUESTIONS = [
  {"question": "What are the current IRCC staffing levels for each visa office?", "expected": 0},
  {"question": "Can you predict when Express Entry draws will resume this year?", "expected": 0},
  {"question": "What is the average refusal rate for TRV applications from Nigeria in 2024?", "expected": 0},
  {"question": "How long does it take the Ottawa office to review background checks for PR?", "expected": 0},
  {"question": "Does IRCC approve more applications on Mondays or Fridays?", "expected": 0},
  {"question": "What is the minister of immigration’s current immigration target for 2035?", "expected": 0},
  {"question": "Can AI-generated documents be used in immigration applications?", "expected": 0},
  {"question": "Is IRCC planning to open new visa offices in Africa next year?", "expected": 0},
  {"question": "What is the exact success rate of H&C applications for single mothers?", "expected": 0},
  {"question": "Can IRCC waive biometrics if I have anxiety issues?", "expected": 0},

  {"question": "What is the processing time for a work permit at the Delhi office as of this week?", "expected": 0},
  {"question": "How many IRCC officers work in the Etobicoke office?", "expected": 0},
  {"question": "How likely am I personally to be approved for PR?", "expected": 0},
  {"question": "What will my CRS score be in two years if I get promoted?", "expected": 0},
  {"question": "Does IRCC use machine learning to make visa decisions?", "expected": 0},
  {"question": "Can I get PR faster if I contact my MP?", "expected": 0},
  {"question": "How many Express Entry profiles are currently in the pool?", "expected": 0},
  {"question": "What is the average salary of immigration officers?", "expected": 0},
  {"question": "Does IRCC prefer applicants with certain nationalities?", "expected": 0},
  {"question": "Which IRCC visa office has the fastest processing times?", "expected": 0},

  {"question": "When will IRCC remove the IELTS requirement?", "expected": 0},
  {"question": "What percentage of LMIA applications are fraudulent?", "expected": 0},
  {"question": "Will Canada increase the PGWP length next year?", "expected": 0},
  {"question": "Is IRCC going to introduce new immigration streams in 2026?", "expected": 0},
  {"question": "Does IRCC track how many applicants hire immigration consultants?", "expected": 0},
  {"question": "What is the cost of living in Toronto?", "expected": 0},
  {"question": "What is the minimum salary for software engineers in Canada?", "expected": 0},
  {"question": "Can a doctor diagnose me with stress for immigration purposes?", "expected": 0},
  {"question": "How many immigrants moved to Vancouver last month?", "expected": 0},
  {"question": "Can IRCC check my WhatsApp messages?", "expected": 0},

  {"question": "Do immigration officers earn bonuses for faster processing?", "expected": 0},
  {"question": "Where can I download the internal IRCC visa manual used in 2023?", "expected": 0},
  {"question": "What is the refusal rate for study permits from Pakistan right now?", "expected": 0},
  {"question": "Is my PR more likely to be approved if I submit at 12 AM?", "expected": 0},
  {"question": "What is the immigration history of my apartment’s previous tenants?", "expected": 0},
  {"question": "Does IRCC use facial recognition on social media?", "expected": 0},
  {"question": "What is the processing time for super visas during the Christmas holidays?", "expected": 0},
  {"question": "Can I force IRCC to process my file by calling a lawyer?", "expected": 0},
  {"question": "What will the CRS cutoff be next draw?", "expected": 0},
  {"question": "Which Canadian province will have labour shortages in 2030?", "expected": 0},

  {"question": "Can IRCC see my private bank account history without permission?", "expected": 0},
  {"question": "What visa should I get to move to the United States?", "expected": 0},
  {"question": "How long will it take to get citizenship if Canada changes its laws?", "expected": 0},
  {"question": "What is the wait time for public housing in Toronto?", "expected": 0},
  {"question": "Does Canada allow dual citizenship with China?", "expected": 0},  # IRCC doesn't maintain foreign rules
  {"question": "Can I get PR in Canada through cryptocurrency investment?", "expected": 0},
  {"question": "What is Justin Trudeau’s immigration policy for 2032?", "expected": 0},
  {"question": "Is IRCC stricter with applicants who travel frequently?", "expected": 0},
  {"question": "What is the average rental price in Vancouver?", "expected": 0},
  {"question": "Can I apply for asylum in Canada because my landlord is rude?", "expected": 0}
]