FROM public.ecr.aws/lambda/python:3.11-arm64

ENV HF_HUB_DISABLE_HF_XET=1

RUN pip install --no-cache-dir \
    "numpy==1.26.4" \
    "pandas>=2.2.0,<3.0.0" \
    "pyarrow==14.0.2"

RUN pip install --no-cache-dir "huggingface_hub>=0.19.0,<1.0.0"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./scraping ./scraping

